config/routes.rb
Rails.application.routes.draw do

  # Startseite => PostsController/list
  get "/", to: "posts#list"

  get "posts/new", to: "posts#new"
  post "posts/create", to: "posts#create"

  get "posts", to: "posts#list"

  get "posts/edit/:id", to: "posts#edit", as: "posts_edit"
  put "posts/update", to: "posts#update"

  get "posts/delete/:id", to: "posts#delete", as: "posts_delete"

  get "posts/:id", to: "posts#read", as: "posts_read"

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def read
  	@posts = Post.find(params[:id])
  end

  def create
  	post = Post.create({
  	  :subject => params[:subject],
  	  :entry => params[:entry]
  	})

  	redirect_to posts_read_path(post[:id])
  end

  def list
    # Alle Posts aus der Datenbank laden
    # und in @posts speichern
    @posts = Post.all

    # app/views/posts/list.html.erb laden
    # render "posts/list"
  end

  def edit
    @post = Post.find(params[:id])
  end

  def delete
    Post.find(params[:id]).delete
    redirect_to posts_path
  end

  def update
    Post.update(params[:id], {
      :subject => params[:subject],
      :entry => params[:entry]
      })
    redirect_to posts_read_path(params[:id])
  end

  def new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ManuBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/welcome.html.erb
Internet

app/views/posts/edit.html.erb
<h1>Blog editieren</h1>

  <%= form_tag "/posts/update", method: "put" do %>
	<div>
		<label for="subject">Subject</label>
		<input type="text" name="subject" value="<%= @post.subject %>">
	</div>
	<div>
		<label for="entry">Entry</label>
		<input type="text" name="entry" value="<%= @post.entry %>">
	</div>

	<input type="hidden" name="id" value="<%= @post.id %>">
	
	<div>
		<input type="submit">
	</div>

<% end %>

app/views/posts/list.html.erb
<!-- http://localhost:3000/posts/new -->
<a href="<%= posts_new_path %>"> neu </a>
<hr>
<!--
	@posts = [
		post1,
		post2,
		...
	]
-->
<% @posts.each do |post| %>
	<div> <%= post.subject %> </div>
	<div> <%= post.entry %> </div>
	<div> 
		<a href="<%= posts_edit_path(post.id) %>"> editieren </a>
		<a href="<%= posts_delete_path(post.id) %>"> löschen </a>
	</div>
	<hr>
<% end %>

app/views/posts/new.html.erb
<h1>Neuer Blogpost</h1>

  <%= form_tag "/posts/create", method: "post" do %>
	<div>
		<label for="subject">Subject</label>
		<input type="text" name="subject">
	</div>
	<div>
		<label for="entry">Entry</label>
		<input type="text" name="entry">
	</div>

	<div>
		<input type="submit">
	</div>

<% end %>

app/views/posts/read.html.erb
<div>  <%= @posts[:subject] %> </div>
<div>  <%= @posts[:entry] %> </div>